# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = []
description = ""
language = "Typescript"
manifest_version = 2
name = "fastly-caching-repro"
service_id = "5sdsCrcYoSMoWPaqi99No0"

[local_server]

  [local_server.backends]

    [local_server.backends.example]
      url = "https://webhook.site"

[scripts]
  build = "npm run build"

[setup]

  [setup.backends]

    [setup.backends.example]
      address = "webhook.site"
      port = 443
