# See https://developer.fastly.com/reference/fastly-toml/

language = "Typescript"
manifest_version = 2
name = "fastly-caching-repro"

[setup.backends.example]
address = "https://webhook.site/"
port = 443

[local_server]

[local_server.backends]

[local_server.backends.example]
url = "https://webhook.site/"

[scripts]
build = "npm run build"
